name = "durabcast"
main = "src/index.ts"
compatibility_date = "2024-07-18"

[[env.test.durable_objects.bindings]]
class_name = "BroadcastMessage"
name = "BROADCAST_MESSAGE"

[[env.test.migrations]]
tag = "v1"
new_classes = ["BroadcastMessage"]