name = "durable-objects-list"
main = "src/index.ts"
compatibility_date = "2024-07-30"

[[durable_objects.bindings]]
class_name = "BroadcastMessage"
name = "BROADCAST_MESSAGE"

[[migrations]]
tag = "v1"
new_classes = ["BroadcastMessage"]