name: "Cache Node Modules"
description: "Caches node_modules using actions/cache"
inputs:
  path:
    description: "Path to the node_modules to cache"
    required: true
runs:
  using: "composite"
  steps:
    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: ${{ inputs.path }}
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json', '**/yarn.lock', '**/pnpm-lock.yaml', '**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-
