name: CI
on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run the CI on"
        required: true
        default: "main"

jobs:
  setup:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.event.inputs.branch }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.event.inputs.branch }}

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache node_modules
        uses: ./.github/actions/cache-node-modules
        with:
          path: "**/node_modules"

      - name: Install dependencies
        run: bun install

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.event.inputs.branch }}

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache node_modules
        uses: ./.github/actions/cache-node-modules
        with:
          path: "**/node_modules"

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.event.inputs.branch }}

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache node_modules
        uses: ./.github/actions/cache-node-modules
        with:
          path: "**/node_modules"

      - name: Install dependencies
        run: bun install

      - name: Run linter
        run: bun run lint

  typecheck:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.event.inputs.branch }}

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache node_modules
        uses: ./.github/actions/cache-node-modules
        with:
          path: "**/node_modules"

      - name: Install dependencies
        run: bun install

      - name: Run typecheck
        run: bun run typecheck

  build:
    runs-on: ubuntu-latest
    needs: [setup, test, lint, typecheck]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.event.inputs.branch }}

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache node_modules
        uses: ./.github/actions/cache-node-modules
        with:
          path: "**/node_modules"

      - name: Install dependencies
        run: bun install

      - name: Build
        run: |
            bun run build
            bunx publint
