name: CI
on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run the CI on"
        required: true
        default: "main"

env:
  PNPM_VERSION: 9.12.1

jobs:
  setup:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.event.inputs.branch }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.event.inputs.branch }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Cache node_modules
        uses: ./.github/actions/cache-node-modules
        with:
          path: "**/node_modules"

      - name: Install dependencies
        run: pnpm install

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.event.inputs.branch }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Cache node_modules
        uses: ./.github/actions/cache-node-modules
        with:
          path: "**/node_modules"

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm run test

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.event.inputs.branch }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Cache node_modules
        uses: ./.github/actions/cache-node-modules
        with:
          path: "**/node_modules"

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm run lint

  typecheck:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.event.inputs.branch }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Cache node_modules
        uses: ./.github/actions/cache-node-modules
        with:
          path: "**/node_modules"

      - name: Install dependencies
        run: pnpm install

      - name: Run typecheck
        run: pnpm run typecheck

  build:
    runs-on: ubuntu-latest
    needs: [setup, test, lint, typecheck]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.event.inputs.branch }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Cache node_modules
        uses: ./.github/actions/cache-node-modules
        with:
          path: "**/node_modules"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: |
          pnpm run build
          pnpx publint
