name: PR PreRelease
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache node_modules
        uses: ./.github/actions/cache-node-modules
        with:
          path: "**/node_modules"

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - run: bunx pkg-pr-new publish
